# Generated by Django 5.1.4 on 2024-12-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='notetype',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
